/**
 * Generated from Scryfall set:om1.
 *
 * Keep this catalog offline so tournament ingestion never depends on Scryfall
 * availability or rate limits. Refresh only if the source data is revalidated.
 */
export const OMENPATHS_TO_PAPER = new Map<string, string>([
	["A Most Helpful Weaver", "Origin of Spider-Man"],
	["A Trail of Teacups", "Kraven's Last Hunt"],
	["Ademi of the Silkchutes", "Spectacular Spider-Man"],
	["Aggressive Symbiosis", "Alien Symbiosis"],
	["Alenni, Brood Recruiter", "Silk, Web Weaver"],
	["Alessos and Pras, Acrobats", "Spider-Man India"],
	["Ancestral Carvings", "Pictures of Spider-Man"],
	["Angler's Shield", "Biorganic Carapace"],
	["Arachnomania", "Spider-Verse"],
	["Arala, Hedron Scaler", "Beetle, Legacy Criminal"],
	["Archangler's Skyrod", "Web-Shooters"],
	["Argyr, Tidal Spinner", "Spider-Byte, Web Warden"],
	["Bane-Marked Leonin", "Venomized Cat"],
	["Basil, Cabaretti Loudmouth", "Flash Thompson, Spider-Fan"],
	["Bayo, Irritable Instructor", "Electro, Assaulting Battery"],
	["Belion, the Parched", "Hydro-Man, Fluid Felon"],
	["Borys, the Spider Rider", "Scarlet Spider, Ben Reilly"],
	["Brako, Heartless Hunter", "Kraven the Hunter"],
	["Cactarantula Saddle", "Spider-Suit"],
	["Caldaia Brawlers", "Inner Demons Gangsters"],
	["Cam and Farrik, Havoc Duo", "Hobgoblin, Mantled Marauder"],
	["Carlo, Suave Schemer", "Prowler, Clawed Thief"],
	["Carriage of Dreams", "Passenger Ferry"],
	["Chizak, Apex Arachnosaur", "Spider-Rex, Daring Dino"],
	["Chosen by Valgavoth", "With Great Power . . ."],
	["Cirina Bargainspinner", "Sun-Spider, Nimble Webber"],
	["Clandestine Work", "Risky Research"],
	["Confessor's Bindings", "Rent Is Due"],
	["Crash, Reckless Endrider", "Shriek, Treblemaker"],
	["Cren of the Spider Brood", "Ultimate Spider-Man"],
	["Cren, Undercity Dreamer", "Miles Morales"],
	["Crime-Scene Instructor", "Selfless Police Captain"],
	["Cruel Caracals", "Kraven's Cats"],
	["Damning Caress", "Venom's Hunger"],
	["Darval, Whose Web Protects", "Spider-Man, Web-Slinger"],
	["Data Scrubber", "Mechanical Mobster"],
	["Deathflame Burst", "Electro's Bolt"],
	["Demera, Soul of a Spider", "Mary Jane Watson"],
	["Desecrex, Gift of Servitude", "Carnage, Crimson Chaos"],
	["Detect Intrusion", "Spider-Sense"],
	["Diligent Webkeepers", "Web-Warriors"],
	["Dreadfang, Loathed by Fans", "Kraven, Proud Predator"],
	["Drix Interception", "Amazing Acrobatics"],
	["Druneth, Reviver of the Hive", "Jackal, Genius Geneticist"],
	["Duskmourn's Claim", "Parker Luck"],
	["Eccentric Arachnologist", "Guy in the Chair"],
	["Egrix the Bile Bulwark", "Gwenom, Remorseless"],
	["Error-9, Viral Node", "Living Brain, Mechanical Marvel"],
	["Exclusive Nightclub", "Oscorp Industries"],
	["Eztli of the Thousand Moons", "Starling, Aerial Ally"],
	["Fateweaver", "Radioactive Spider"],
	["Favored Fighter", "Professional Wrestler"],
	["Fearsome Ridgeline", "Daily Bugle Building"],
	["Fire-Brained Scheme", "Heroes' Hangout"],
	["Fizik, Etherium Mechanic", "Iron Spider, Stark Upgrade"],
	["Fleem, Goben's Creation", "Green Goblin"],
	["Freestrider Aces", "Wild Pack Squad"],
	["Full-Throttle Fanatic", "Taxi Driver"],
	["Galvanized Workforce", "Angry Rabble"],
	["Generous Betty Wray", "Silver Sable, Mercenary Leader"],
	["Giantcraft Helm", "Doc Ock's Tentacles"],
	["Gloria, the Great Armorer", "Araña, Heart of the Spider"],
	["Goben, Gene-Splice Savant", "Norman Osborn"],
	["Goro Rel, Scourge to Spiders", "Spider-Slayer, Hatred Honed"],
	["Hex of Undeath", "Behold the Sinister Six!"],
	["Hide in Mundanity", "Spider-Man No More"],
	["Janai and Hoppy, Roofskippers", "Spider-Girl, Legacy Hero"],
	["Kavaero, Mind-Bitten", "Superior Spider-Man"],
	["Kazuo, Ruthless Rival", "Shocker, Unshakable"],
	["Kephon, Rage Incubator", "Stegron the Dinosaur Man"],
	["King of the Coldblood Curse", "Lizard, Connors's Curse"],
	["Kivni, Orb Weaver", "Scarlet Spider, Kaine"],
	["Knife Trick", "Pumpkin Bombardment"],
	["Kraza, the Swarm as One", "Spider-Punk"],
	["Kroble, Envoy of the Bog", "Spider-Man Noir"],
	["Kumonosu, the Watchful", "SP"],
	["Lavaborn Goblins", "Raging Goblinoids"],
	["Lavabrink Repels the Magmaloth", "Maximum Carnage"],
	["Lazlo, Enthusiastic Accuser", "J. Jonah Jameson"],
	["Leyline Weaver", "Spider Manifestation"],
	["Lively Leap", "Thwip!"],
	["Lost in Littjara", "The Clone Saga"],
	["Luis, Pompous Pillager", "Morlun, Devourer of Spiders"],
	["Makdee and Itla, Skysnarers", "Spider-Woman, Stunning Savior"],
	["Margot, On the Case", "Wraith, Vicious Vigilante"],
	["Merata, Neuron Hacker", "Lady Octopus, Inspired Inventor"],
	["Miasmic Mist", "Sandman's Quicksand"],
	["Mothwing Shroud", "Web Up"],
	["Neach, Pinnacle Pariah", "Doctor Octopus, Master Planner"],
	["Nia, Fabled Skyclimber", "Ghost-Spider"],
	["Nia, Skysail Storyteller", "Gwen Stacy"],
	["Nill, Vessel of Valgavoth", "Tombstone, Career Criminal"],
	["Nu and Sumi, Career Criminals", "Green Goblin, Revenant"],
	["Obscura Alleylurkers", "Doc Ock's Henchmen"],
	["Olx, Mouth to Many Eyes", "Madame Web, Clairvoyant"],
	["Opulent Valet", "News Helicopter"],
	["Orris, Last of the Web Lords", "Ezekiel Sims, Spider-Totem"],
	["Outsmart the Amateur", "School Daze"],
	["Ozor, Chronicler of Collapse", "Doc Ock, Sinister Scientist"],
	["Perfected Pastry", "Bagel and Schmear"],
	["Perilous Lunge", "Kapow!"],
	["Phantasmal Vision", "Mysterio's Phantasm"],
	["Phenomena Recorder", "Peter Parker's Camera"],
	["Pinnacle Research Team", "Oscorp Research Team"],
	["Principled Referee", "Daily Bugle Reporters"],
	["Qoneus, Horizon Splicer", "The Spot, Living Portal"],
	["Quint's Insight", "Shadow of the Goblin"],
	["Reality Fulcrum", "Interdimensional Web Watch"],
	["Remarkable Readings", "Friendly Neighborhood"],
	["Remorseless Coup", "The Spot's Portal"],
	["Restless Razorkin", "Superior Foes of Spider-Man"],
	["Rhilex the Accursed", "Agent Venom"],
	["Rishei, Getaway Accomplice", "Vulture, Scheming Scavenger"],
	["Rizna, the Spider-Crowned", "Spinneret and Spiderling"],
	["Rouse the Swarm", "Wall Crawl"],
	["Ruzic, Booed but Victorious", "Ultimate Green Goblin"],
	["Sadistic String-Puller", "Spider-Islanders"],
	["Sarn of the Silken Throne", "Spider-UK"],
	["Scions of the Ur-Spider", "Cosmic Spider-Man"],
	["Scorvus Ames, Crimelord", "Scorpion, Seething Striker"],
	["Scuttling Spidercoach", "Spider-Mobile"],
	["Selesnya Archivist", "Damage Control Crew"],
	["Skittering Kitten", "Masked Meower"],
	["Skv'x the Augmenter", "Symbiote Spider-Man"],
	["Snatch Back", "Whoosh!"],
	["Spectral Restitching", "Hide on the Ceiling"],
	["Steelweb Surveyor", "Spider-Bot"],
	["Stitcher's Wings", "Rocket-Powered Goblin Glider"],
	["Surris, Silk-Tech Vanguard", "Amazing Spider-Man"],
	["Surris, Spidersilk Innovator", "Peter Parker"],
	["Tarantusk, Unwisely Awoken", "Spider-Ham, Peter Porker"],
	["Tearle, Entropic Hunger", "Morbius the Living Vampire"],
	["Temple Trap", "Steel Wrecking Ball"],
	["Tethex, Gift of Malice", "Venom, Evil Unleashed"],
	["The Clutter Cluster", "Spiders-Man, Heroic Horde"],
	["The House Grows Hungry", "The Death of Gwen Stacy"],
	["The Infernus", "Molten Man, Inferno Incarnate"],
	["The Scouring Stormsoul", "Sandman, Shifting Scoundrel"],
	["The Terminus of Return", "The Soul Stone"],
	["The Watcher on the Road", "Mysterio, Master of Illusion"],
	["Through the Omenpath", "Web of Life and Destiny"],
	["Treat Trolley", "Hot Dog Cart"],
	["Uharis, the Stormspinner", "Spider-Man 2099"],
	["Vazin, Two-Faced Trickster", "Chameleon, Master of Disguise"],
	["Verilax the Havenskin", "Anti-Venom, Horrifying Healer"],
	["Vexed Bots", "Flying Octobot"],
	["Viggo, End of Ig's Crossing", "Venom, Lethal Protector"],
	["Viggo, Enforcer of Ig's Crossing", "Eddie Brock"],
	["Vinewoven Chariot", "Subway Train"],
	["Wardens of Silverweb Summit", "Spider-Gwen, Free Spirit"],
	["Wekhdu, Midnight Hunter", "Swarm, Being of Bees"],
	["Withar, Cocoon Keeper", "Mister Negative"],
	["Wonderweave Aerialist", "Skyward Spider"],
	["Wrench, Speedway Saboteur", "Black Cat, Cunning Thief"],
	["Xecau, Predation's Shadow", "Rhino, Barreling Brute"],
	["Yera and Oski, Weaver and Guide", "Arachne, Psionic Weaver"],
	["Zan, Tunnelweb Explorer", "Spider-Man, Brooklyn Visionary"],
	["Zora, Spider Fancier", "Aunt May"],
]);
